
/**
* optimization.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* Monday, November 26, 2018 12:39:32 AM CET
*/

public interface optimization extends optimizationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface optimization
